// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'history-clear-confirm'
  | 'history-clear-done'
  | 'history-clear-title'
  | 'message-no-collections'
  | 'message-no-readable-items'
  | 'message-open-failed'
  | 'picker-clear-all'
  | 'picker-covered'
  | 'picker-duplicate'
  | 'picker-message'
  | 'picker-no-collections'
  | 'picker-select-all'
  | 'picker-title'
  | 'pref-add-collection'
  | 'pref-clear-history'
  | 'pref-clear-history-help'
  | 'pref-help'
  | 'pref-refresh-collections'
  | 'pref-title'
  | 'pref-whitelist-description'
  | 'prefs-collection-active'
  | 'prefs-collection-missing'
  | 'prefs-remove-button'
  | 'prefs-title'
  | 'toolbar-button-tooltip';
